# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a103f80b6baa1b8c4f480caf8a93fb1365a937531ef624903c3a0319e96001194a46cb58db2484c80f7647b017724799ce7ce4b2e0d2a1b59f6de2205139cd4f

test:
  secret_key_base: db6273f1742703658db756d993aa34ffe3c362ec8fe573b393cfb3b3f47599b692d7c5fb8fb2165a087e55f3fae9ea6dd90f4df8476d7c92ffe0b4026c249f1c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
